truncate table tb_convidado;

insert into tb_convidado (nome_convidado, nome_convidado_visualizacao, nick_instagram, id_funcao_eclesiastica)
values 
('Ronald Gustavo','Ronald Gustavo','@ronaldgustavo',1),
('Lukão Carvalho','Lukão Carvalho','@lukaocarvalho',5),
('Antonio Filho','Antonio Filho','@antoniofillhooficial',1),
('ALBERTO SILVA','ALBERTO SILVA','@PR.ALBERTOSILVA',1),
('Cleuton Soares','Cleuton Soares','@cleutondosimplesatitude',1),
('Davi Leal','Davi Leal','@prdavileal',1),
('Fernando Toledo','Fernando Toledo','@prfernandotoledo',1),
('Augusto Antonio Brito','Augusto Brito','@augustoabrito',6),
('ALEX DIAS','ALEX DIAS','@ALEXDIASOFICIAL_01',1),
('BRENO WASHINGTON','BRENO WASHINGTON','@BRENO_VOZEVIOLAO',5),
('BRUNA KARLA','BRUNA KARLA','@BRUNAKARLA',5),
('Bruno Tavares','Bruno Tavares','@prbrunotavares',1),
('BRUNA LOPES','BRUNA LOPES','@BRUNALOFEER',5),
('CASSIANE','CASSIANE','@cassianecantora',5),
('CARLINHOS FELIX','CARLINHOS FELIX','@carlinhosfelix',5),
('CELINA RIBEIRO','CELINA RIBEIRO','@CELINA_RIBEIRO.OFC',5),
('CLAYTON QUEIROZ','CLAYTON QUEIROZ','@CLAYTONQUEIROZOFICIAL',5),
('Cicera Regina Quintas','Cicera Regina','@cicerareginaquintas',6),
('CRISTINA RIBEIRO','CRISTINA RIBEIRO','@CRISTINARIBEIRO932',5),
('DANIEL WAGNER','DANIEL WAGNER','@MINISTERIODANIELWAGNER',1),
('Daniel Monte de Araújo','Daniel Araújo', '@danielmontedearaujo', 6),
('DANIELLE CRISTINA','DANIELLE CRISTINA','@DANIELLECRISTINAOFICIAL',5),
('DANIELLE CRISTINA','DANIELLE CRISTINA','@DANIELLECRISTINAOFICIAL',8),
('DÉBORA LIMA','DÉBORA LIMA','@DEBORA.SOUZALIMA',6),
('DÉBORA LIMA','DÉBORA LIMA','@DEBORA.SOUZALIMA',16),
('EDSON HANNA','EDSON HANNA','@HANNAEDSON',1), 
('EDIVALDO SANTANA','EDIVALDO SANTANA','@edivaldo.santana.104',1), 
('ELIEZER DI TARSIS','ELIEZER DI TARSIS','@ELIEZERDITARSIS',5),
('Erivelton Nunes','Erivelton Nunes','@pr.erivelton.nunes',1),
('EMERSON PEDROSA','EMERSON PEDROSA','@EMERSONPEDROSAOFICIAL',5),
('EMERSON PINHEIRO','EMERSON PINHEIRO','@PR.EMERSONOFICIAL',1),
('ERIKA DUARTE','ERIKA DUARTE','@REAF.ERIKADUARTE',8),
('EYSHILA SANTOS','EYSHILA SANTOS','@EYSHILASANTOS',8),
('ELIZETE MALAFAIA','ELIZETE MALAFAIA','@elizetemalafaia',8),
('EZEQUIEL ALEGRIA','EZEQUIEL ALEGRIA','@ALEGRIAEZEQUIEL',5),
('FÁBIO AMARAL','FÁBIO AMARAL','@PR_FABIOAMARAL',1),
('FERNANDA BRUM','FERNANDA BRUM','@BRUMFERNANDA',5),
('FERNANDA BRUM','FERNANDA BRUM','@BRUMFERNANDA',8),
('FLAVIA ARRAIS','FLAVIA ARRAIS','@FLAVIAARRAIS',5),
('GABRIEL GUEDES','GABRIEL GUEDES','@GABRIELGUEDES',5),
('GABRIEL LOPES','GABRIEL LOPES','@bieel_loppes',1),
('GIULIANO DIAS','GIULIANO DIAS','@GIULIANODIAS',1),
('GUSTAVO KNAUER','GUSTAVO KNAUER','@GUSTAVOKNAUER',1),
('HERLAN NOGUEIRA','HERLAN NOGUEIRA','@HERLAN.NOGUEIRA',1),
('IARA CALIXTO','IARA CALIXTO','@IARACALIXTO.OFC',5),
('INGRID TRASSI','INGRID TRASSI','@INGRID_TRASSIOFC',5),
('IRAQUITAN ALVES','IRAQUITAN ALVES','@IRAQUITANALVESS',1),
('HELEN RODRIGUES','HELEN RODRIGUES','@HELENRUIVAH',6),
('ITALO RIBEIRO','ITALO RIBEIRO','@ITALORIBEIROOFICAL',5),
('JANAINA PIMENTEL','JANAINA PIMENTEL','@janaina.pimentel40',5),
('JESSICA AUGUSTO','JESSICA AUGUSTO','@AJESSICAAUGUSTO',5),
('JOCYMAR FONSECA','JOCYMAR FONSECA','@jocymarfonseca',1),
('JULIANA FERRON','JULIANA FERRON','@juliana.ferron',6),
('JULIO CÉSAR','JULIO CÉSAR','@LIVEJULIOCESAR',5),
('Julio Vertullo','Julio Vertullo','@juliovertullo',1),
('KELLEN BYANCA','KELLEN BYANCA','@KELLENBYANCA',5),
('KEZIA OLIVEIRA','KEZIA OLIVEIRA','@PRAKEZIAOLIVEIRA',5),
('KEZYA NUNES','KEZYA NUNES','@KEZYANUNES',5),
('LEONARDO SILVA','LEONARDO SILVA','@PRLEONARDOSILVAOFICIAL',1),
('LEYDI MURILHO','LEYDI MURILHO','@LEIDYMURILHO',5),
('LILIAN AZEVEDO','LILIAN AZEVEDO ','@LILIANAZEVEDO1',5),
('MARCELO GONÇALVES','MARCELO GONÇALVES','@MARCELOGONCALVESREAL',5),
('MARCELO ZAPPA','MARCELO ZAPPA','@MARCELLOZAPPA59',5),
('MARY COSTA','MARY COSTA','@miss.marycosta',9),
('MARTA KOBB','MARTA KOBB','@KOBBMARTA',1),
('MELK VILLAR','MELK VILLAR','@MELKVILLAR',5),
('MIDIAN LIMA','MIDIAN LIMA','@PRAMIDIANLIMA',1),
('MISAIAS OLIVEIRA','MISAIAS OLIVEIRA','@MISAIASOLIVEIRA',5),
('LILIAN MALVEZI','LILIAN MALVEZI','@LILIANMALVEZI',9),
('RAQUEL LIMA','RAQUEL LIMA','@MISSRAQUELLIMA',9),
('NEIDE MARTINS','NEIDE MARTINS','@NEIDEMARTINSOFICIAL',5),
('NERILDO ACCIOLY','NERILDO ACCIOLY','@PRNERILDOACCIOLY',1),
('PALAVRA TOCADA','PALAVRA TOCADA','@PALAVRATOCADA',5),
('PALOMA POSSI','PALOMA POSSI','@PALOMAPOSSI',5),
('PAOLA CARLA','PAOLA CARLA','@PAOLACARLA_OFICIAL',5),
('PATRÍCIA PARISI','PATRÍCIA PARISI','@PATRICIAPARISIOFICIAL',5),
('PATRÍCIA FERREIRA','PATRÍCIA FERREIRA','@patriciaferreiraoficial_',5),
('PAULA PEREIRA','PAULA PEREIRA','@PAULAPEREIRAOFICIAL',5),
('ADRIEL BATISTA','ADRIEL BATISTA','@PR.ADRIELBATISTA',1),
('ALYSSON BARBOSA','ALYSSON BARBOSA','@ALYSSON.BARBOSAA',1),
('ANDRÉ MATIAS','ANDRÉ MATIAS','@ANDREMATIASPR',1),
('BISNAGA','BISNAGA','@PASTORBISNAGA',1),
('CAIO CESAR','CAIO CESAR','@EVCAIOCESAR',1),
('CARLOS ALBERTO','CARLOS ALBERTO','@PASTORCARLOSALBERTOFERREIRA',1),
('CLEBER FARIAS','CLEBER FARIAS','@PRCLEBERFARIAS',1),
('CRISTIAN OLIVEIRA','CRISTIAN OLIVEIRA','@PR.CRISTIANOLIVEIRA',1),
('DANIEL PEREIRA','DANIEL PEREIRA','@PRDANIELPEREIRA',1),
('DEIVID PATENTE','DEIVID PATENTE','@PR.DEIVID_PATENTE',1),
('DIEGO CUNHA','DIEGO CUNHA','@DIEGOF2CUNHA',1),
('DYEGO NERY','DYEGO NERY','@dyegonery',1),
('DJALMA PINHO','DJALMA PINHO','@DJALMAPINHO',1),
('EDSON RODRIGUES','EDSON RODRIGUES','@pastoredsonrodrigues',1),
('ELIEL SILVA','ELIEL SILVA','@PASTORELIELSILVA',1),
('ELIO JOAQUIM','ELIO JOAQUIM','@ELIOJOAQUIM',1),
('FAMÍLIA MVA','FAMÍLIA MVA','@familiamva',5),
('FAMÍLIA LEÃO','FAMÍLIA LEÃO', '@familia_leao',5),
('FELIPE HENRIQUE','FELIPE HENRIQUE','@felipeehenriquee',1),
('FILIPE DANIEL','FILIPE DANIEL','@FILIPEDANIELOFICIAL',1),
('FRANCISCO OLIVEIRA','FRANCISCO OLIVEIRA','@PR_FRANCISCOOLIVEIRA',1),
('FRED ARRAIS','FRED ARRAIS','@FREDARRAIS',1),
('GERSON COSTA','GERSON COSTA','@PRGERSONCOSTAOFICIAL',1),
('GEZIEL LIMA','GEZIEL LIMA','@PRGEZIELLIMA',1),
('JOA CAITANO','JOA CAITANO','@JOACAITANO_OFICIAL',1),
('JUNIOR CHAVES','JUNIOR CHAVES','@PRJUNIORCHAVES',1),
('LEILTON BRITO','LEILTON BRITO','@PR.LEILTONBRITO',1),
('MARCOS MARINHO','MARCOS MARINHO','@EV_MARCOS_PAULO',1),
('MARCOS LEITE','MARCOS LEITE','@prmarcosleite77',1),
('MARQUINHOS MENEZES','MARQUINHOS MENEZES','@MARQUINHOSMENEZESOFICIAL',1),
('MIQUEIAS OLIVEIRA','MIQUEIAS OLIVEIRA','@PRMIQUEIASOLIVEIRA',1),
('MOISES LEOPOLDINO','MOISES LEOPOLDINO','@PR_MOISES_LEOPOLDINO',1),
('NIVALDO NASSIFF','NIVALDO NASSIFF','@NSNASSIFF',1),
('ODILON SANTOS','ODILON SANTOS','@ODILONSANTOSPR',1),
('ANTONIO ORESTES','ANTONIO ORESTES','@ANTONIO_ORESTES',1),
('OSVALDO BRAZ FARIAS','OSVALDO BRAZ','@ev.osvaldobraz',1),
('OTONIEL GOMES','OTONIEL GOMES','@PASTOROTONIELGOMESFERNANDA',1),
('PAULO HENRIQUE','PAULO HENRIQUE','@PRPAULOOFICIAL',1),
('PEDRO ROSA','PEDRO ROSA','@PEDROPAULOROSA',1),
('ROGÉRIO GASPARINO','ROGÉRIO GASPARINO','@PRROGERIO.GASPARINO',1),
('SAMUEL DO AMOR','SAMUEL DO AMOR','@SAMUELDOAMOR',1),
('THIAGO DE ASSIS','THIAGO DE ASSIS','@PRTHIAGODEASSIS',1),
('THIAGO MOURA','THIAGO MOURA','@THIAGOMOURA_OFICIALL',1),
('VICTORINO JR.','VICTORINO JR.','@VICTORINOSJR',1),
('MATHEUS LEYTE','MATHEUS LEYTE','@MATHEUSLEYTE_OFICIAL',1),
('RAQUEL MIRANDA','RAQUEL MIRANDA','@RAQUELMIRANDAOFICIAL',5),
('RENAN RODRIGUES','RENAN RODRIGUES','@RENAN.RODRIGUES135',1),
('ROBINSON MONTEIRO','ROBINSON MONTEIRO','@ROBINSONMONTEIRO',5),
('Romildo Resende','Romildo Resende','@pr.romildoresende',1),
('SAMUEL MACEI','SAMUEL MACEI','@SAMUELMACEIOFICIAL',5),
('SAMUEL MESSIAS','SAMUEL MESSIAS','@SAMUELMESSIASOFICIAL',5),
('SILMAR COELHO','SILMAR COELHO','@SILMARCOELHO',6),
('SORAYA MORAES','SORAYA MORAES','@SORAYAMORAES',5),
('SUELEN FRANCIS','SUELEN FRANCIS','@suelenfrancs',5),
('SUELEN MANGOLIN','SUELEN MANGOLIN','@SUELENMANGOLIN',6),
('JEFFERSON NASCIMENTO','JEFFERSON NASCIMENTO','@SUELENMANGOLIN',6),
('TONY MARTINS','TONY MARTINS','@pr.tonymartinss',1),
('TALITHA PEREIRA','TALITHA PEREIRA','@talithapereira',8),
('TAMIRES PEREIRA','TAMIRES PEREIRA','@TAMIS.TAMIRESPEREIRA',1),
('VALÉRIA LOCATELLI','VALÉRIA LOCATELLI','@VALERIALOCATELLIOFICIAL',5),
('VÂNIA COSTA','VÂNIA COSTA','@vaniam_costa',6),
('VIVIANE GONÇALVES','VIVIANE GONÇALVES','@VIVI_CHEIADEVIDA',5),
('WELLINGTON PAES','WELLINGTON PAES','@WELLINGTON.PAES',1),
('Pitte Goiabeira','Pitte Goiabeira','@pittegoiabeira',5),
('Fran Rolim','Fran Rolim','@franrolim',5),

-- VOCAL
('MICHEL TAKESHI','MICHEL TAKESHI','@MICHELTAKESHI',17),
('ESTER SOUZA LIMA','ESTER LIMA','@ester_souza.lima',17),
('SANNY GONÇALVES','SANNY GONÇALVES','@hericasannyoficial',17),
('EDER LIMA','EDER LIMA','@eder_limah',17),
('EMILLY IZABELY','EMILLY IZABELY','@emilly_izabely_',17),
('GIULIA MENDES','GIULIA MENDES','@_giumendesss',17),
('WESLEY MENDES','WESLEY MENDES','@_weslymendes',17),
('ESTER SANTOS','ESTER SANTOS','@estersantos1402',17),
('MIRIAM SILVEIRA','MIRIAM SILVEIRA','@miriamsilveira8',17),
('INGRID FERRANTE','INGRID FERRANTE','@ingridferrantereal',17),
('ALAFY PRADO','ALAFY PRADO','@_ALAFYP',17),
('GABRIEL CAITANO','GABRIEL CAITANO','@gabrielcaitanooficial',17),
('KEILA CAITANO','KEILA CAITANO','@keilacaitanofc',17),
('MARESSA BULHÕES','MARESSA BULHÕES','@ma.bulhoes',17),
('ROSLAINE RODRIGUES','ROSLAINE RODRIGUES','@roslaine.rodrigues',17),
('REBECA PRADO','REBECA PRADO','@_REE_PRADO',17),
('Davidson Soares','Davidson Soares', '@davidson_soares_oficial',17),
('Samara Soares','Samara Soares', '@sama.soares',17),
('Jaqueline Oliveira','Jaqueline Oliveira','@jaqueline.soliver',17),
('Mizasoul Lima','Mizasoul Lima','@mizasoul',17),
('Eduardo Luiz','Eduardo Luiz', '@edlss',17),
('Rebeca Oliveira','Rebeca Oliveira','@rebeca_ncoliveira',17),
('Carla Rubiana','Carla Rubiana','@cahrubiana',17),
('Tawana Dias','Tawana Dias','@tawana.dias',17),
('Lilian Santos','Lilian Santos','@liliansanttos_ofc',17),

-- teclas
('Guilherme Alves','Guilherme Alves','@allveskeys',11),
('João Almeida','João Almeida','@joaoalmeidaa_tcls',11),
('Abimeleque','Abimeleque', '@abimelequeprado',11),
('Berg Cosfer','Berg Cosfer','@berg.cosfer',11),
('Elan Ferreira','Elan Ferreira','@elan.teclas',11),

-- bateras
('Antony Silva','Antony Silva','@antonysilva_drummer',12),
('Felipe Souza Lima','Felipe Lima','@felpsz_souza',12),
('Ranieri Meireles','Ranieri Meireles','@ranierimeireles',12),
('Edney','Edney','@edneyfx',12),
('Luiz Fabiano','Luizinho','@luizfabiano01',12),
('Guilherme Oliveira','Guilherme Oliveira','@guiih_oliveira15',12),
('Lucas Brian','Lucas Brian','@lucasbrian_',12),

-- baixistas
('Daniel Soares','Dan','@danisoares22_',13),
('Micael Jodan Da Silva Santos','Micael Jodan','@micaeljodandasilva',13),
('Diego Santos', 'Diego Santos', '@dieegoo_santtos',13),
('Orlando Junior', 'Orlando Junior', '@orlandojnr_',13),
('Davi Braz', 'Davi Braz', '@davibraz_bx',13),


-- sax
('Pedro Lucena','Pedro Lucena','@pedrolucenasax',14), 

-- violao
('Sidney Henrique','Sidney Henrique','@sidney_s.h.a_decora',15),

-- guitarras
('David Paz','David Paz','@davidpazferreira',16),
('Elpidio Junior','Elpidio Juior','@projetoclikar',16),
('Gabriel Monsalve','Gabriel Monsalve','@gcmguittar',16),
('Junior Duncam','Junior Duncam','@juniorduncam',16),
('Henrique','Henrique','@',16),
('Herbert Coelho','Herbert Coelho','@herbert_coelho', 16);


UPDATE tb_convidado set nick_instagram = lcase(nick_instagram), hash_convidado = sha1(id_convidado);


select distinct nick_instagram 
from tb_convidado; 

select distinct ucase(nome_convidado), concat('', lcase(nick_instagram ) , '') as nick
from tb_convidado 
where  nome_convidado like '%barbosa%'
order by nome_convidado;

select c.nome_convidado_visualizacao, c.nick_instagram, f.nm_funcao_eclesiastica
from tb_convidado as c 
inner join tb_funcao_eclesiastica as f on f.id_funcao_eclesiastica = c.id_funcao_eclesiastica 
WHERE c.id_funcao_eclesiastica > 10
order by f.nm_funcao_eclesiastica, c.nome_convidado_visualizacao;
-- Janeiro ()
